services:
  postgres:
    image: postgres:16-alpine
    container_name: fichas_tecnicas_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fichas_network

volumes:
  postgres_data:
    driver: local

networks:
  fichas_network:
    driver: bridge
